print("Work so hard")
print()
print(".. that they think \n the Aliens did it")
print("\\")
print("one file to show","what it means","to use print funciton","while it puts spaces between multiple string outputs")
print("KEYWORD Argument 'end'", "to change the default NEWLINE to SPACE..", end=" ")
print("This previous NEWLINE is now replaced with a SPACE")
print("Using 'sep' Keyword Argument","to change field separators","to dash", sep="-")
print("Using both","the 'sep'","and the 'end'","together",sep="*",end="$\n$")
print("and we got this")
print("Programming","Essentials","in",sep="***",end="...")
print("Python")
