print("    *")
print("   * *")
print("  *   *")
print(" *     *")
print("***   ***")
print("  *   *")
print("  *   *")
print("  *****")
print("-" *10)
print("      **")
print("     *  *")
print("    *    *")
print("   *      *")
print("  *        *")
print(" *          *")
print("*****   *****")
print("    *   *")
print("    *   *")
print("    *****")
